name: "Textile Bucket - Deploy"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bucket_push:
    runs-on: ubuntu-latest
    name: Push Textile Bucket
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.2
    - name: push action
      id: push
      uses: textileio/github-action-buckets@v18
      with:
        key: ${{ secrets.TEXTILE_ACCOUNT_KEY }}
        secret: ${{ secrets.TEXTILE_ACCOUNT_SECRET }}
        bucket: "oceandt"
        thread: "bafkvhrnmx5yqlecrsn5pz7vvlw6y2akqeywvmcba7y47wx3xsyskpwy"
        path: "."
    - run: echo "bucket - ${{ steps.push.outputs.key  }}"
    - run: echo "ipfs - ${{ steps.push.outputs.ipfs }}"
    - run: echo "ipfs link - ${{ steps.push.outputs.ipfsUrl }}"
    - run: echo "ipns - ${{ steps.push.outputs.ipns }}"
    - run: echo "ipns link - ${{ steps.push.outputs.ipnsUrl }}"
    - run: echo "hub - ${{ steps.push.outputs.hub }}"
    - run: echo "www - ${{ steps.push.outputs.www }}"
